dist: trusty
sudo: required

# This moves Kubernetes specific config files.
env:
- CHANGE_MINIKUBE_NONE_USER=true

addons:
  sonarcloud:
    organization: "vikkasyousaf-github"

jdk:
  - oraclejdk8

before_script:

script:
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'

