dist: trusty
sudo: required

# This moves Kubernetes specific config files.
env:
- CHANGE_MINIKUBE_NONE_USER=true

addons:
  sonarcloud:
    organization: "vikkasyousaf-github"

jdk:
  - oraclejdk8

before_script:

script:
  - sonar-scanner -Dsonar.login= 453070edd3a796d26de528dc66d9c0cc8b5a4902

cache:
  directories:
    - '$HOME/.sonar/cache'

