dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "sonarcloud"
    token:
      secure: "c52e68fc191870f23c6bebbc5fe2010cd077ce5c"

jdk:
  - oraclejdk8

script:
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'

