dist: trusty
sudo: required

# This moves Kubernetes specific config files.
env:
- CHANGE_MINIKUBE_NONE_USER=true

addons:
  sonarcloud:
    organization: "vikkasyousaf-github"

jdk:
  - oraclejdk8

before_script:

script:
  - sonar-scanner -Dsonar.login= 2061291aa3ffc2ac55b9b570705f57f3451b053c

  - kubectl cluster-info

cache:
  directories:
    - '$HOME/.sonar/cache'

